export const OpenSourceLicense = [
  {
    "libraryName": "@baronha/react-native-multiple-image-picker",
    "version": "0.4.13",
    "_license": "MIT",
    "_description": "react-native-multiple-image-picker enables application to pick images and videos from multiple smart album in iOS/Android, similar to the current facebook app.",
    "homepage": "https: //github.com/baronha/react-native-multiple-image-picker#readme",
    "author": { "name": "Baron Ha.", "email": "baronn.ha@gmail.com", "url": "https://github.com/baronha" },
    "repository": { "type": "git", "url": "git+https://github.com/baronha/react-native-multiple-image-picker.git" },
  },
  {
    "libraryName": "@react-native - async - storage / async - storage",
    "version": "1.17.10",
    "_license": "MIT",
    "_description": "Asynchronous, persistent, key - value storage system for React Native.",
    "homepage": "https: //github.com/react-native-async-storage/async-storage#readme",
    "author": { "name": "Krzysztof Borowy", "email": "hello@krizzu.dev" },
    "repository": { "type": "git", "url": "git+https://github.com/react-native-async-storage/async-storage.git" },
  },
  {
    "libraryName": "@react-native - community / art",
    "version": "1.2.0",
    "_license": "MIT",
    "_description": "React Native module that allows you to draw vector graphics",
    "homepage": "https: //github.com/react-native-community/react-native-art",
    "author": { "name": "@react-native-community" },
  },
  {
    "libraryName": "@react-native - community / masked - view",
    "version": "0.1.11",
    "_license": "MIT",
    "_description": "React Native MaskedView component",
    "homepage": "https: //github.com/react-native-community/react-native-masked-view#readme",
    "author": { "name": "Mike Nedosekin", "email": "crespo8800@gmail.com" },
    "repository": { "type": "git", "url": "git+https://github.com/react-native-community/react-native-masked-view.git" }
  },
  {
    "libraryName": "@react-native-material/core",
    "version": "1.3.7",
    "_license": "MIT",
    "_description": "Modular and customizable Material Design UI components for React Native",
    "homepage": "https://github.com/yamankatby/rn-material#readme",
    "author": { "name": "Yaman KATBY", "email": "me@yamankatby.com", "url": "https://yamankatby.com/" },
    "repository": { "type": "git", "url": "git+https://github.com/yamankatby/rn-material.git" },
  },
  {
    "libraryName": "@react-native-seoul/kakao-login",
    "version": "5.2.4",
    "_license": "MIT",
    "_description": "React Native Module for Kakao Login",
    "homepage": "https://github.com/react-native-seoul/react-native-kakao-login#readme",
    "author": { "name": "dooboolab" },
    "repository": { "type": "git", "url": "git+https://github.com/react-native-seoul/react-native-kakao-login.git" },
  },
  {
    "libraryName": "@react-navigation / bottom - tabs",
    "version": "6.4.0",
    "_license": "MIT",
    "_description": "Bottom tab navigator following iOS design guidelines",
    "homepage": "https: //github.com/react-navigation/react-navigation#readme",
    "repository": { "type": "git", "url": "git+https://github.com/react-navigation/react-navigation.git", "directory": "packages/bottom-tabs" },
  },
  {
    "libraryName": "@react-navigation / native",
    "version": "6.0.13",
    "_license": "MIT",
    "_description": "React Native integration for React Navigation",
    "homepage": "https: //reactnavigation.org",
    "repository": { "type": "git", "url": "git+https://github.com/react-navigation/react-navigation.git", "directory": "packages/native" },
  },
  {
    "libraryName": "@react-navigation/stack",
    "version": "6.3.4",
    "_license": "MIT",
    "_description": "Stack navigator component for iOS and Android with animated transitions and gestures",
    "homepage": "https://reactnavigation.org/docs/stack-navigator/",
    "repository": { "type": "git", "url": "git+https://github.com/react-navigation/react-navigation.git", "directory": "packages/stack" },
  },
  {
    "libraryName": "@rneui/base",
    "version": "4.0.0-rc.7",
    "_license": "MIT",
    "_description": "Cross Platform React Native UI Toolkit",
    "homepage": "https://reactnativeelements.com/",
    "author": { "name": "RNE Core Team" },
    "repository": { "type": "git", "url": "git+https://github.com/react-native-elements/react-native-elements.git", "directory": "packages/base" }
  },
  {
    "libraryName": "@rneui/themed",
    "version": "4.0.0-rc.7",
    "_license": "MIT",
    "_description": "Cross Platform React Native UI Toolkit",
    "homepage": "https://reactnativeelements.com/",
    "author": { "name": "RNE Core Team" },
    "repository": { "type": "git", "url": "git+https://github.com/react-native-elements/react-native-elements.git", "directory": "packages/themed" }
  },
  {
    "libraryName": "aws-sdk",
    "version": "2.1251.0",
    "_license": "Apache-2.0",
    "_description": "AWS SDK for JavaScript",
    "homepage": "https://github.com/aws/aws-sdk-js",
    "author": { "name": "Amazon Web Services", "url": "https://aws.amazon.com/" },
    "repository": { "type": "git", "url": "git://github.com/aws/aws-sdk-js.git" },
  },
  {
    "libraryName": "axios",
    "version": "0.27.2",
    "_license": "MIT",
    "_description": "Promise based HTTP client for the browser and node.js",
    "homepage": "https://axios-http.com",
    "author": { "name": "Matt Zabriskie" },
    "repository": { "type": "git", "url": "git+https://github.com/axios/axios.git" },
  },
  {
    "libraryName": "base-64",
    "version": "1.0.0",
    "_license": "MIT",
    "_description": "A robust base64 encoder/decoder that is fully compatible with `atob()` and `btoa()`, written in JavaScript.",
    "homepage": "https://mths.be/base64",
    "author": { "name": "Mathias Bynens", "url": "https://mathiasbynens.be/" },
    "repository": { "type": "git", "url": "git+https://github.com/mathiasbynens/base64.git" },
  },
  {
    "libraryName": "date-fns",
    "version": "2.29.3",
    "_license": "MIT",
    "_description": "Modern JavaScript date utility library",
    "homepage": "https://github.com/date-fns/date-fns#readme",
    "repository": { "type": "git", "url": "git+https://github.com/date-fns/date-fns.git" },
  },
  {
    "libraryName": "multer",
    "version": "1.4.5 - lts.1",
    "_license": "MIT",
    "_description": "Middleware for handling`multipart/form-data`.",
    "homepage": "https: //github.com/expressjs/multer#readme",
    "repository": { "type": "git", "url": "git+https://github.com/expressjs/multer.git" },
  },
  {
    "libraryName": "multer-s3",
    "version": "3.0.1",
    "_license": "MIT",
    "_description": "Streaming multer storage engine for AWS S3",
    "homepage": "https://github.com/badunk/multer-s3#readme",
    "author": { "name": "badunk" },
    "repository": { "type": "git", "url": "git+https://github.com/badunk/multer-s3.git" },
  },
  {
    "libraryName": "react",
    "version": "18.1.0",
    "_license": "MIT",
    "_description": "React is a JavaScript library for building user interfaces.",
    "homepage": "https://reactjs.org/",
    "repository": { "type": "git", "url": "git+https://github.com/facebook/react.git", "directory": "packages/react" },
  },
  {
    "libraryName": "react - native",
    "version": "0.70.3",
    "_license": "MIT",
    "_description": "A framework for building native apps using React",
    "homepage": "https:/github.com/facebook/react-native#readme",
    "repository": { "type": "git", "url": "git+https://github.com/facebook/react-native.git" },
  },
  {
    "libraryName": "react - native - actionsheet",
    "version": "2.4.2",
    "_license": "MIT",
    "_description": "Cross platform ActionSheet.This component implements a custom ActionSheet  and provides the same way to drawing it on the defferent platforms(iOS and Android).Actually, In order to keep the best effect, it still uses the ActionSheetIOS on iOS.", "homepage": "https: //github.com/beefe/react-native-actionsheet#readme",
    "author": { "name": "xiaoyann" },
    "repository": { "type": "git", "url": "git+https://github.com/beefe/react-native-actionsheet.git" },
  },
  {
    "libraryName": "react-native-calendars",
    "version": "1.1291.1",
    "_license": "MIT",
    "_description": "React Native Calendar Components",
    "homepage": "https://github.com/wix/react-native-calendars#readme",
    "author": { "name": "Wix.com" },
    "repository": { "type": "git", "url": "git+https://github.com/wix/react-native-calendars.git" },
  },
  {
    "libraryName": "react - native - chart - kit",
    "version": "6.12.0",
    "_license": "MIT",
    "_description": "If you're looking to **build a website or a cross-platform mobile app** – we will be happy to help you! Send a note to clients@ui1.io and we will be in touch with you shortly.",
    "homepage": "https: //github.com/indiespirit/react-native-chart-kit",
    "repository": { "type": "git", "url": "git+https://github.com/indiespirit/react-native-chart-kit.git" },
  },
  {
    "libraryName": "react-native-charts-wrapper",
    "version": "0.5.11",
    "_license": "MIT",
    "_description": "A react-native charts support both android and iOS.",
    "homepage": "https://github.com/wuxudong/react-native-charts-wrapper",
    "author": { "name": "wuxudong" },
    "repository": { "type": "git", "url": "git+https://github.com/wuxudong/react-native-charts-wrapper.git" }
  },
  {
    "libraryName": "react-native-date-picker",
    "version": "4.2.6",
    "_license": "MIT",
    "_description": "A datetime picker for React Native. In-modal or inlined. Supports Android and iOS.",
    "homepage": "https://github.com/henninghall/react-native-date-picker",
    "author": { "name": "henninghall" },
    "repository": { "type": "git", "url": "git+ssh://git@github.com/henninghall/react-native-date-picker.git" },
  },
  {
    "libraryName": "react - native - gesture - handler",
    "version": "2.8.0",
    "_license": "MIT",
    "_description": "Experimental implementation of a new declarative API for gesture handling in react - native",
    "homepage": "https: //github.com/software-mansion/react-native-gesture-handler#readme",
    "author": { "name": "Krzysztof Magiera", "email": "krzys.magiera@gmail.com" },
    "repository": { "type": "git", "url": "git+https://github.com/software-mansion/react-native-gesture-handler.git" },
  },
  {
    "libraryName": "react-native-global-props",
    "version": "1.1.5",
    "_description": "A simple javascript implementation to add custom, default props to react - native components.",
    "homepage": "https: //github.com/Ajackster/react-native-global-props#readme",
    "author": { "name": "Andrew L. Jackson", "url": "https://github.com/Ajackster" },
    "repository": { "type": "git", "url": "git+https://github.com/Ajackster/react-native-global-props.git" },
  },
  {
    "libraryName": "react - native - image - picker",
    "version": "4.10.0",
    "_license": "MIT",
    "_description": "A React Native module that allows you to use native UI to select media from the device library or directly from the camera",
    "homepage": "https: //github.com/react-native-image-picker/react-native-image-picker",
    "author": { "name": "Johan du Toit", "url": "Johan-dutoit" },
    "repository": { "type": "git", "url": "git+https://github.com/react-native-image-picker/react-native-image-picker.git" },
  },
  {
    "libraryName": "react-native-modal-datetime-picker",
    "version": "14.0.0",
    "_license": "MIT",
    "_description": "A react-native datetime-picker for Android and iOS",
    "homepage": "https://github.com/mmazzarolo/react-native-modal-datetime-picker",
    "author": { "name": "Mazzarolo Matteo" },
    "repository": { "type": "git", "url": "git+https://github.com/mmazzarolo/react-native-modal-datetime-picker.git" },
  },
  {
    "libraryName": "react-native-paper",
    "version": "4.12.5",
    "_license": "MIT",
    "_description": "Material design for React Native",
    "homepage": "https://callstack.github.io/react-native-paper",
    "repository": { "type": "git", "url": "git+https://github.com/callstack/react-native-paper.git" },
  },
  {
    "libraryName": "react-native-pie-chart",
    "version": "2.0.2",
    "_license": "MIT",
    "_description": "pie chart for react native",
    "homepage": "https://github.com/genexu/react-native-pie-chart#readme",
    "author": { "name": "Gene Xu" },
    "repository": { "type": "git", "url": "git+https://github.com/genexu/react-native-pie-chart.git" },
  },
  {
    "libraryName": "react - native - reanimated",
    "version": "2.12.0",
    "_license": "MIT",
    "_description": "More powerful alternative to Animated library for React Native.",
    "homepage": "https: //github.com/software-mansion/react-native-reanimated#readme",
    "author": { "name": "Krzysztof Magiera", "email": "krzys.magiera@gmail.com" },
    "repository": { "type": "git", "url": "git+https://github.com/software-mansion/react-native-reanimated.git" },
  },
  {
    "libraryName": "react-native-reanimated-carousel",
    "version": "3.1.5",
    "_license": "MIT",
    "_description": "Simple carousel component.fully implemented using Reanimated 2.Infinitely scrolling, very smooth.",
    "homepage": "https://github.com/dohooo/react-native-reanimated-carousel#readme",
    "author": { "name": "Doho", "email": "zhaodonghao586@outlook.com", "url": "https://github.com/dohooo" },
    "repository": { "type": "git", "url": "git+https://github.com/dohooo/react-native-reanimated-carousel.git" },
  },
  {
    "libraryName": "react - native - safe - area - context",
    "version": "4.4.1",
    "_license": "MIT",
    "_description": "A flexible way to handle safe area, also works on Android and web.",
    "homepage": "https: //github.com/th3rdwave/react-native-safe-area-context#readme",
    "author": { "name": "Janic Duplessis", "email": "janicduplessis@gmail.com" },
    "repository": { "type": "git", "url": "git+https://github.com/th3rdwave/react-native-safe-area-context.git" },
  },
  {
    "libraryName": "react-native-screens",
    "version": "3.18.2",
    "_license": "MIT",
    "_description": "Native navigation primitives for your React Native app.",
    "homepage": "https://github.com/software-mansion/react-native-screens#readme",
    "author": { "name": "Krzysztof Magiera", "email": "krzys.magiera@gmail.com" },
    "repository": { "type": "git", "url": "git+https://github.com/software-mansion/react-native-screens.git" },
  },
  {
    "libraryName": "react - native - snap - carousel",
    "version": "3.9.1", "_license": "BSD - 3 - Clause",
    "_description": "Swiper / carousel component for React Native with previews, multiple layouts, parallax images, performant handling of huge numbers of items, and RTL support.Compatible with Android & iOS.",
    "homepage": "https: //github.com/archriss/react-native-snap-carousel",
    "author": { "name": "Archriss", "email": "contact@archriss.com", "url": "github.com/archriss" },
    "repository": { "type": "git", "url": "github.com/archriss/react-native-snap-carousel" },
  },
  {
    "libraryName": "react-native-splash-screen",
    "version": "3.3.0",
    "_license": "MIT",
    "_description": "A splash screen for react-native, hide when application loaded ,it works on iOS and Android.",
    "homepage": "https://github.com/crazycodeboy/react-native-splash-screen#readme",
    "author": { "name": "crazycodeboy" },
    "repository": { "type": "git", "url": "git+https://github.com/crazycodeboy/react-native-splash-screen.git" },
  },
  {
    "libraryName": "react - native - vector - icons",
    "version": "9.2.0",
    "_license": "MIT",
    "_description": "Customizable Icons for React Native with support for NavBar / TabBar, image source and full styling.",
    "homepage": "https: //github.com/oblador/react-native-vector-icons",
    "author": { "name": "Joel Arvidsson", "email": "joel@oblador.se" },
    "repository": { "type": "git", "url": "git://github.com/oblador/react-native-vector-icons.git" },
  },
  {
    "libraryName": "react - redux",
    "version": "8.0.5",
    "_license": "MIT",
    "_description": "Official React bindings for Redux",
    "homepage": "https: //github.com/reduxjs/react-redux",
    "author": {
      "name": "Dan Abramov", "email": "dan.abramov@me.com",
      "url": "https://github.com/gaearon"
    },
    "repository": { "type": "git", "url": "git+https://github.com/reduxjs/react-redux.git" },
  },
  {
    "libraryName": "redux",
    "version": "4.2.0",
    "_license": "MIT",
    "_description": "Predictable state container for JavaScript apps",
    "homepage": "http://redux.js.org",
    "repository": { "type": "git", "url": "git+https://github.com/reduxjs/redux.git" },
  },
  {
    "libraryName": "rnpm",
    "version": "1.9.0",
    "_license": "MIT",
    "_description": "React Native Package Manager",
    "homepage": "https: //github.com/rnpm/rnpm#readme",
    "author": {
      "name": "Amazing React Native Community",
      "url": "https://github.com/facebook/react-native"
    },
    "repository": { "type": "git", "url": "git+https://github.com/rnpm/rnpm.git" },
  }
]